// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjnecqekyuvfavgidyld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqbmVjcWVreXV2ZmF2Z2lkeWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNTQ4MDEsImV4cCI6MjA1MzYzMDgwMX0.qrb2fp9_7TNcTHoltMCYRdbhGy0bxo7OrWP4qEHkvhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);